'use client'
import {Inter} from "next/font/google";
import React from "react";
import './typography.scss';
import './reusable-styles.scss';
import Providers from "@/app/SignInButton/Providers/Provider";
import '../i18n';
import {Provider} from "react-redux";
import store from "@/store/storeState/store";

const inter = Inter({subsets: ["latin"]});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode; }>) {
  return (
    <Provider store={store}>
      <html lang="bg">
      <body className={inter.className}>
      <Providers>
        {children}
      </Providers>
      </body>
      </html>
    </Provider>
  );
}
