import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Home from "./Home-page/page";
import Navigation from "@/app/Navigation-component/navigation";
import React from "react";
import Link from "next/link";
import './reusable-styles.scss';
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className="">
    <div className="nav-bar">
      <Navigation/>
    </div>
    {children}
    </body>
    </html>
  );
}
